
-- ADDRESS TABLE
CREATE TABLE ADDRESS (
    ID INT NOT NULL,
    STREET VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    ZIP_CODE VARCHAR(20),
    PRIMARY KEY (ID)
);

-- DEVICE TABLE
CREATE TABLE DEVICE (
    ID INT NOT NULL,
    DEVICE_NAME VARCHAR(20),
    TYPE VARCHAR(20),
    COST DECIMAL(10, 2),
    QUANTITY INT,
    PRIMARY KEY (ID)
);

-- USER TABLE
CREATE TABLE USER (
    ID INT NOT NULL,
    USER_NAME VARCHAR(20),
    EMAIL VARCHAR(20),
    PHONE INT,
    JOB VARCHAR(20),
    STATUS CHAR(25),
    COST DECIMAL(10, 2),
    ADDRESS_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID)
);

-- PROJECT TABLE
CREATE TABLE PROJECT (
    ID INT NOT NULL,
    PROJECT_NAME VARCHAR(20),
    TYPE VARCHAR(20),
    STATUS VARCHAR(20),
    START_DATE DATE,
    END_DATE DATE,
    ADDRESS_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID)
);

-- ASSIGNMENT
CREATE TABLE ASSIGNMENT (
    ID INT NOT NULL,
    PROJECT_ID INT,
    USER_ID INT,
    DEVICE_ID INT,
    START_DATE DATE,
    FINISH_DATE DATE,
    COST DECIMAL(10, 2),
    PRIMARY KEY (ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE(ID)
);

USE PROJECT; --use the database/schema named PROJECT.
SHOW TABLES FROM project; --show all the tables that got created under it.